<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Suppress Microsoft.OpenApi advisory, set the max depth for mappings as a remediation -->
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-v5pm-xwqc-g5wc" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="*.txt" />
    <None Remove="*.clef" />
    <None Remove="LogFiles\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.SecurityKey" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Injectio" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Arbiter.CommandQuery.Endpoints\Arbiter.CommandQuery.Endpoints.csproj" />
    <ProjectReference Include="..\..\..\src\Arbiter.CommandQuery.MongoDB\Arbiter.CommandQuery.MongoDB.csproj" />
  </ItemGroup>

  <!-- Disable compile-time OpenAPI XML generator -->
  <!-- Temporary workaround for issue with OpenAPI source generator -->
  <!-- https://github.com/dotnet/aspnetcore/issues/64378 -->
  <Target Name="DisableCompileTimeOpenApiXmlGenerator" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Analyzer Remove="@(Analyzer)" Condition="'%(Analyzer.Filename)%(Analyzer.Extension)' == 'Microsoft.AspNetCore.OpenApi.SourceGenerators.dll'" />
    </ItemGroup>
  </Target>

</Project>
