#pragma warning disable MA0051 // Method is too long

using System.Text;

using Arbiter.Mapping.Generators.Infrastructure;
using Arbiter.Mapping.Generators.Models;

namespace Arbiter.Mapping.Generators;

/// <summary>
/// Emits the generated source code for a mapper partial class, including
/// <c>Map</c> and <c>ProjectTo</c> implementations with property assignments.
/// </summary>
public static class MapperWriter
{
    /// <summary>
    /// Generates the complete source text for a mapper partial class.
    /// </summary>
    /// <param name="mapperClass">The mapper model describing source, destination, and property mappings.</param>
    /// <returns>The generated C# source text.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="mapperClass"/> is <see langword="null"/>.</exception>
    public static string Generate(MapperClass mapperClass)
    {
        if (mapperClass is null)
            throw new ArgumentNullException(nameof(mapperClass));

        var builder = new IndentedStringBuilder();

        builder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine()
            .AppendLine("using System;")
            .AppendLine("using System.CodeDom.Compiler;")
            .AppendLine("using System.Linq;")
            .AppendLine("using System.Runtime.CompilerServices;");

        // emit any additional using directives captured from the mapper's source file
        // so that raw expressions referencing external types (e.g. constants from imported
        // namespaces) continue to compile in the generated output
        var standardImports = new HashSet<string>(StringComparer.Ordinal)
        {
            "using System;",
            "using System.CodeDom.Compiler;",
            "using System.Linq;",
            "using System.Runtime.CompilerServices;",
        };

        foreach (var u in mapperClass.Imports.AsArray())
        {
            if (standardImports.Add(u))
                builder.AppendLine(u);
        }

        builder.AppendLine();

        builder
            .Append("namespace ")
            .Append(mapperClass.EntityNamespace)
            .AppendLine(";")
            .AppendLine();

        builder
            .AppendLine("/// <summary>")
            .Append("/// Source generated mapper from <c>")
            .Append(ToXmlDocTypeName(mapperClass.SourceClass.EntityName))
            .Append("</c> to <c>")
            .Append(ToXmlDocTypeName(mapperClass.DestinationClass.EntityName))
            .AppendLine("</c>.")
            .AppendLine("/// </summary>")
            .Append("partial class ")
            .AppendLine(mapperClass.EntityName)
            .IncrementIndent()
            .Append(": global::Arbiter.Mapping.MapperProfile<")
            .Append(mapperClass.SourceClass.FullyQualified)
            .Append(", ")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .AppendLine(">")
            .DecrementIndent()
            .AppendLine("{")
            .IncrementIndent();

        // Generate the mapping method here
        GenerateCreateMapper(builder, mapperClass);
        GenerateCopyMapper(builder, mapperClass);
        GenerateProjectMapper(builder, mapperClass);
        GenerateNestedMappers(builder, mapperClass);

        // close class
        builder
            .DecrementIndent()
            .AppendLine("}");

        return builder.ToString();
    }


    /// <summary>
    /// Emits the <c>Map(TSource?)</c> implementation that creates a new destination instance.
    /// </summary>
    private static void GenerateCreateMapper(IndentedStringBuilder builder, MapperClass mapperClass)
    {
        builder
            .AppendLine("/// <inheritdoc />")
            .Append("[GeneratedCode(\"")
            .Append(ThisAssembly.AssemblyName)
            .Append("\", \"")
            .Append(ThisAssembly.FileVersion)
            .AppendLine("\")]")
            .AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]")
            .Append("public override ")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .Append("? Map(")
            .Append(mapperClass.SourceClass.FullyQualified)
            .AppendLine("? source)")
            .AppendLine("{")
            .IncrementIndent();

        // null check
        builder
            .AppendLine("if (source is null)")
            .AppendLine("    return default;");

        var ctorParams = mapperClass.ConstructorParameters.AsArray();

        var properties = mapperClass.Properties.AsArray();
        var destinationType = mapperClass.DestinationClass.FullyQualified;

        builder.AppendLine();

        if (ctorParams.Length > 0)
        {
            builder.Append("return ");
            WriteConstructorCreation(builder, mapperClass, destinationType, properties, ctorParams, "source", isExpressionTree: false);
            builder.AppendLine(";");
        }
        else
        {
            builder.Append("return ");
            WriteInitializerCreation(builder, mapperClass, destinationType, properties, "source", isExpressionTree: false);
            builder.AppendLine(";");
        }

        // function close
        builder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }

    /// <summary>
    /// Emits the <c>Map(TSource, TDestination)</c> implementation that copies values to an existing destination.
    /// When all non-ignored properties are init-only, emits a method that throws <see cref="NotSupportedException"/>.
    /// </summary>
    private static void GenerateCopyMapper(IndentedStringBuilder builder, MapperClass mapperClass)
    {
        var properties = mapperClass.Properties.AsArray();
        var hasAssignableProperties = false;

        foreach (var property in properties)
        {
            if (!property.IsIgnored && !property.IsReadOnly)
            {
                hasAssignableProperties = true;
                break;
            }
        }

        builder
            .AppendLine("/// <inheritdoc />")
            .Append("[GeneratedCode(\"")
            .Append(ThisAssembly.AssemblyName)
            .Append("\", \"")
            .Append(ThisAssembly.FileVersion)
            .AppendLine("\")]")
            .AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]")
            .Append("public override void Map(")
            .Append(mapperClass.SourceClass.FullyQualified)
            .Append(" source, ")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .AppendLine(" destination)")
            .AppendLine("{")
            .IncrementIndent();

        if (!hasAssignableProperties)
        {
            builder
                .AppendLine("throw new NotSupportedException(\"Map to existing destination is not supported because all destination properties are read-only.\");");
        }
        else
        {
            // null checks
            builder
                .AppendLine("if (source is null)")
                .AppendLine("    throw new ArgumentNullException(nameof(source));")
                .AppendLine()
                .AppendLine("if (destination is null)")
                .AppendLine("    throw new ArgumentNullException(nameof(destination));")
                .AppendLine();

            // foreach property mapping
            foreach (var property in mapperClass.Properties)
            {
                if (property.IsIgnored || property.IsReadOnly)
                    continue;

                builder.Append("destination.").Append(property.DestinationName).Append(" = ");
                WriteSourceExpression(builder, mapperClass, "source", property, isExpressionTree: false);
                builder.AppendLine(";");
            }
        }

        // function close
        builder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }

    /// <summary>
    /// Emits a static field that caches the projection expression and the <c>ProjectTo</c>
    /// implementation that references it, avoiding per-call expression tree allocations.
    /// </summary>
    private static void GenerateProjectMapper(IndentedStringBuilder builder, MapperClass mapperClass)
    {
        var ctorParams = mapperClass.ConstructorParameters.AsArray();

        // emit cached static expression field
        builder
            .Append("private static readonly System.Linq.Expressions.Expression<Func<")
            .Append(mapperClass.SourceClass.FullyQualified)
            .Append(", ")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .AppendLine(">> _projectExpression =");

        var properties = mapperClass.Properties.AsArray();
        var destinationType = mapperClass.DestinationClass.FullyQualified;

        builder
            .IncrementIndent()
            .Append("src => ");

        if (ctorParams.Length > 0)
        {
            WriteConstructorCreation(builder, mapperClass, destinationType, properties, ctorParams, "src", isExpressionTree: true);
        }
        else
        {
            WriteInitializerCreation(builder, mapperClass, destinationType, properties, "src", isExpressionTree: true);
        }

        builder
            .AppendLine(";")
            .DecrementIndent()
            .AppendLine();

        // emit ProjectTo implementation
        builder
            .AppendLine("/// <inheritdoc />")
            .Append("[GeneratedCode(\"")
            .Append(ThisAssembly.AssemblyName)
            .Append("\", \"")
            .Append(ThisAssembly.FileVersion)
            .AppendLine("\")]")
            .Append("public override IQueryable<")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .Append("> ProjectTo(IQueryable<")
            .Append(mapperClass.SourceClass.FullyQualified)
            .AppendLine("> source)")
            .AppendLine("{")
            .IncrementIndent();

        // null check
        builder
            .AppendLine("if (source is null)")
            .AppendLine("    throw new ArgumentNullException(nameof(source));");

        // use cached expression
        builder
            .AppendLine()
            .AppendLine("return source.Select(_projectExpression);");

        // function close
        builder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }


    /// <summary>
    /// Emits a <c>new TDest(arg1, arg2, ...) { remaining = value, ... }</c> expression
    /// using constructor arguments for matched parameters and an object initializer for the rest.
    /// </summary>
    private static void WriteConstructorCreation(
        IndentedStringBuilder builder,
        MapperClass mapperClass,
        string destinationType,
        PropertyMapping[] properties,
        string[] ctorParams,
        string parameterName,
        bool isExpressionTree,
        int depth = 0)
    {
        var ctorParamSet = new HashSet<string>(ctorParams, StringComparer.Ordinal);
        var propertyLookup = new Dictionary<string, PropertyMapping>(StringComparer.Ordinal);

        foreach (var property in properties)
            propertyLookup[property.DestinationName] = property;

        // open constructor call
        builder
            .Append("new ")
            .Append(destinationType)
            .AppendLine("(")
            .IncrementIndent();

        // emit constructor arguments in parameter order
        for (var i = 0; i < ctorParams.Length; i++)
        {
            if (propertyLookup.TryGetValue(ctorParams[i], out var property) && !property.IsIgnored)
            {
                WriteSourceExpression(builder, mapperClass, parameterName, property, isExpressionTree, depth);
            }
            else
            {
                builder.Append("default!");
            }

            if (i < ctorParams.Length - 1)
                builder.AppendLine(",");
        }

        builder.DecrementIndent();

        // collect remaining properties not covered by the constructor
        var remaining = new List<PropertyMapping>();
        foreach (var property in properties)
        {
            if (property.IsIgnored || ctorParamSet.Contains(property.DestinationName))
                continue;

            remaining.Add(property);
        }

        if (remaining.Count == 0)
        {
            // close constructor only
            builder.AppendLine().Append(")");
            return;
        }

        // close constructor, open initializer
        builder
            .AppendLine()
            .AppendLine(")")
            .AppendLine("{")
            .IncrementIndent();

        foreach (var property in remaining)
        {
            builder.Append(property.DestinationName).Append(" = ");
            WriteSourceExpression(builder, mapperClass, parameterName, property, isExpressionTree, depth);
            builder.AppendLine(",");
        }

        builder
            .DecrementIndent()
            .Append("}");
    }

    /// <summary>
    /// Emits a <c>new TDest { Prop = value, ... }</c> expression using object initializer syntax.
    /// </summary>
    private static void WriteInitializerCreation(
        IndentedStringBuilder builder,
        MapperClass mapperClass,
        string destinationType,
        PropertyMapping[] properties,
        string parameterName,
        bool isExpressionTree,
        int depth = 0)
    {
        // open object initializer
        builder
            .Append("new ")
            .AppendLine(destinationType)
            .AppendLine("{")
            .IncrementIndent();

        foreach (var property in properties)
        {
            if (property.IsIgnored)
                continue;

            builder.Append(property.DestinationName).Append(" = ");
            WriteSourceExpression(builder, mapperClass, parameterName, property, isExpressionTree, depth);
            builder.AppendLine(",");
        }

        // close object initializer
        builder
            .DecrementIndent()
            .Append("}");
    }

    /// <summary>
    /// Emits the private static helper methods that deep clone configured nested objects,
    /// collections and dictionaries.
    /// </summary>
    private static void GenerateNestedMappers(IndentedStringBuilder builder, MapperClass mapperClass)
    {
        foreach (var nested in mapperClass.NestedMappings)
        {
            builder
                .Append("[GeneratedCode(\"")
                .Append(ThisAssembly.AssemblyName)
                .Append("\", \"")
                .Append(ThisAssembly.FileVersion)
                .AppendLine("\")]")
                .Append("private static ")
                .Append(nested.DestinationType)
                .Append("? ")
                .Append(nested.MethodName)
                .Append("(")
                .Append(nested.SourceType)
                .AppendLine("? source)")
                .AppendLine("{")
                .IncrementIndent()
                .AppendLine("if (source is null)")
                .AppendLine("    return default;")
                .AppendLine()
                .Append("return ");

            if (nested.Kind == MappingKind.Complex)
            {
                var properties = nested.Properties.AsArray();
                var ctorParams = nested.ConstructorParameters.AsArray();

                if (ctorParams.Length > 0)
                    WriteConstructorCreation(builder, mapperClass, nested.DestinationType, properties, ctorParams, "source", isExpressionTree: false);
                else
                    WriteInitializerCreation(builder, mapperClass, nested.DestinationType, properties, "source", isExpressionTree: false);
            }
            else
            {
                WriteCollectionExpression(builder, nested, "source", "item", isExpressionTree: false, mapperClass, depth: 0);
            }

            builder
                .AppendLine(";")
                .DecrementIndent()
                .AppendLine("}")
                .AppendLine();
        }
    }

    /// <summary>
    /// Emits a LINQ expression that clones each element (or dictionary value) of <paramref name="sourceExpression"/>.
    /// In expression trees the element mapping is inlined; otherwise the element helper method is called.
    /// </summary>
    private static void WriteCollectionExpression(
        IndentedStringBuilder builder,
        NestedMapping nested,
        string sourceExpression,
        string itemName,
        bool isExpressionTree,
        MapperClass mapperClass,
        int depth)
    {
        var suppress = nested.IsElementNullable ? string.Empty : "!";

        if (nested.CollectionKind == CollectionKind.Dictionary)
        {
            builder
                .Append("global::System.Linq.Enumerable.ToDictionary(")
                .Append(sourceExpression)
                .Append(", ")
                .Append(itemName)
                .Append(" => ")
                .Append(itemName)
                .Append(".Key, ")
                .Append(itemName)
                .Append(" => ");

            WriteElementExpression(builder, nested, itemName + ".Value", isExpressionTree, mapperClass, depth);
            builder.Append(suppress).Append(")");
            return;
        }

        var prefix = nested.CollectionKind == CollectionKind.HashSet
            ? "new global::System.Collections.Generic.HashSet<" + nested.ElementDestinationType + ">("
            : string.Empty;

        builder
            .Append(prefix)
            .Append("global::System.Linq.Enumerable.Select(")
            .Append(sourceExpression)
            .Append(", ")
            .Append(itemName)
            .Append(" => ");

        WriteElementExpression(builder, nested, itemName, isExpressionTree, mapperClass, depth);
        builder.Append(suppress).Append(")");

        if (nested.CollectionKind == CollectionKind.HashSet)
            builder.Append(")");
        else if (nested.CollectionKind == CollectionKind.Array)
            builder.Append(".ToArray()");
        else
            builder.Append(".ToList()");
    }

    /// <summary>
    /// Emits the clone expression for a single collection element.
    /// </summary>
    private static void WriteElementExpression(
        IndentedStringBuilder builder,
        NestedMapping nested,
        string elementExpression,
        bool isExpressionTree,
        MapperClass mapperClass,
        int depth)
    {
        if (!isExpressionTree)
        {
            builder.Append(nested.ElementMethodName).Append("(").Append(elementExpression).Append(")");
            return;
        }

        var element = FindNestedMapping(mapperClass, nested.ElementMethodName);
        if (element == null)
        {
            builder.Append(elementExpression);
            return;
        }

        WriteInlineComplexExpression(builder, mapperClass, element, elementExpression, depth + 1);
    }

    /// <summary>
    /// Emits an inline, expression-tree compatible clone of a nested object:
    /// <c>value == null ? null : new TDest { ... }</c>.
    /// </summary>
    private static void WriteInlineComplexExpression(
        IndentedStringBuilder builder,
        MapperClass mapperClass,
        NestedMapping nested,
        string valueExpression,
        int depth)
    {
        builder
            .Append(valueExpression)
            .Append(" == null ? null : ");

        var properties = nested.Properties.AsArray();
        var ctorParams = nested.ConstructorParameters.AsArray();

        if (ctorParams.Length > 0)
            WriteConstructorCreation(builder, mapperClass, nested.DestinationType, properties, ctorParams, valueExpression, isExpressionTree: true, depth);
        else
            WriteInitializerCreation(builder, mapperClass, nested.DestinationType, properties, valueExpression, isExpressionTree: true, depth);
    }

    /// <summary>
    /// Finds a nested helper model by method name.
    /// </summary>
    private static NestedMapping? FindNestedMapping(MapperClass mapperClass, string methodName)
    {
        foreach (var nested in mapperClass.NestedMappings)
        {
            if (string.Equals(nested.MethodName, methodName, StringComparison.Ordinal))
                return nested;
        }

        return null;
    }

    /// <summary>
    /// Writes the value expression for a configured nested property, wrapping the source access with
    /// a helper call (in-memory) or an inline clone (expression tree).
    /// </summary>
    private static void WriteNestedExpression(
        IndentedStringBuilder builder,
        MapperClass mapperClass,
        string parameterName,
        PropertyMapping property,
        bool isExpressionTree,
        int depth)
    {
        var nested = FindNestedMapping(mapperClass, property.NestedMethodName);
        var direct = property with { Kind = MappingKind.Direct, NestedMethodName = string.Empty, IsDestinationNullable = true };

        if (nested == null || (isExpressionTree && nested.Kind == MappingKind.Dictionary))
        {
            var fallback = property with { Kind = MappingKind.Direct, NestedMethodName = string.Empty };
            WriteSourceExpression(builder, mapperClass, parameterName, fallback, isExpressionTree, depth);
            return;
        }

        var valueBuilder = new IndentedStringBuilder();
        WriteSourceExpression(valueBuilder, mapperClass, parameterName, direct, isExpressionTree, depth);
        var valueExpression = valueBuilder.ToString();

        if (!isExpressionTree)
        {
            builder.Append(property.NestedMethodName).Append("(").Append(valueExpression).Append(")");
            if (!property.IsDestinationNullable)
                builder.Append("!");
            return;
        }

        builder.Append("(");

        if (nested.Kind == MappingKind.Complex)
        {
            WriteInlineComplexExpression(builder, mapperClass, nested, "(" + valueExpression + ")", depth);
        }
        else
        {
            builder
                .Append("(")
                .Append(valueExpression)
                .Append(") == null ? null : ");

            var itemName = "item" + depth.ToString(System.Globalization.CultureInfo.InvariantCulture);
            WriteCollectionExpression(builder, nested, "(" + valueExpression + ")", itemName, isExpressionTree: true, mapperClass, depth);
        }

        builder.Append(")");
        if (!property.IsDestinationNullable)
            builder.Append("!");
    }


    /// <summary>
    /// Writes the source-side expression for a single property assignment, choosing between
    /// raw expressions, null-safe navigation, or direct property access.
    /// </summary>
    private static void WriteSourceExpression(
        IndentedStringBuilder builder,
        MapperClass mapperClass,
        string parameterName,
        PropertyMapping property,
        bool isExpressionTree,
        int depth = 0)
    {
        if (property.Kind != MappingKind.Direct && !string.IsNullOrEmpty(property.NestedMethodName))
        {
            WriteNestedExpression(builder, mapperClass, parameterName, property, isExpressionTree, depth);
            return;
        }

        // raw expression mode
        if (!string.IsNullOrEmpty(property.SourceExpression))
        {
            WriteRawExpression(builder, parameterName, property);
            return;
        }

        var path = property.SourcePath.AsArray();
        if (path.Length == 0)
            return;

        var segmentNullable = property.SourceSegmentNullable.AsArray();
        var hasAnyNullable = Array.Exists(segmentNullable, static n => n);

        if (path.Length > 1 && hasAnyNullable && isExpressionTree)
        {
            // expression trees don't support ?. operator (CS8072)
            // use nested ternaries for each nullable segment
            WriteExpressionTreeNavigation(builder, parameterName, path, segmentNullable, property);
        }
        else if (path.Length > 1 && hasAnyNullable)
        {
            // in-memory null safety: use ?. only after nullable segments
            builder.Append(parameterName);

            for (int i = 0; i < path.Length; i++)
            {
                // use ?. before this segment if the previous segment is nullable
                var nullConditional = i > 0 && segmentNullable[i - 1];
                builder.Append(nullConditional ? "?." : ".").Append(path[i]);
            }

            if (property.IsDestinationNullable)
            {
                // destination allows null, no fallback needed
            }
            else if (property.IsDestinationString)
            {
                builder.Append(" ?? string.Empty");
            }
            else
            {
                builder.Append(" ?? default!");
            }
        }
        else
        {
            // direct property access: source.Id or source.Tenant.Name
            builder.Append(parameterName);
            for (int i = 0; i < path.Length; i++)
                builder.Append(".").Append(path[i]);
        }
    }

    /// <summary>
    /// Emits a raw source expression with lambda parameter name substitution.
    /// </summary>
    private static void WriteRawExpression(
        IndentedStringBuilder builder,
        string parameterName,
        PropertyMapping property)
    {
        var expression = property.SourceExpression;
        var sourceParam = property.SourceExpressionParameter;

        // substitute the lambda parameter name with the target parameter name
        if (!string.IsNullOrEmpty(sourceParam)
            && !string.Equals(sourceParam, parameterName, StringComparison.Ordinal))
        {
            expression = ReplaceParameterAccess(expression, sourceParam, parameterName);
        }

        builder.Append(expression);
    }

    /// <summary>
    /// Replaces occurrences of <paramref name="oldParameter"/> followed by <c>.</c> with
    /// <paramref name="newParameter"/> followed by <c>.</c>, but only when the match
    /// appears at a word boundary (not preceded by a letter, digit, or underscore).
    /// This prevents false matches inside property names (e.g. <c>Items.</c> matching <c>s.</c>).
    /// </summary>
    private static string ReplaceParameterAccess(string expression, string oldParameter, string newParameter)
    {
        var oldAccess = oldParameter + ".";
        var newAccess = newParameter + ".";

        var index = expression.IndexOf(oldAccess, StringComparison.Ordinal);
        if (index < 0)
            return expression;

        var result = new StringBuilder(expression.Length + ((newAccess.Length - oldAccess.Length) * 2));
        var start = 0;

        while (index >= 0)
        {
            var isWordBoundary = index == 0 || !IsIdentifierChar(expression[index - 1]);

            if (isWordBoundary)
            {
                result.Append(expression, start, index - start);
                result.Append(newAccess);
                start = index + oldAccess.Length;
            }
            else
            {
                result.Append(expression, start, index + 1 - start);
                start = index + 1;
            }

            index = expression.IndexOf(oldAccess, start, StringComparison.Ordinal);
        }

        result.Append(expression, start, expression.Length - start);

        return result.ToString();
    }

    /// <summary>
    /// Converts a fully-qualified type name to a valid XML doc <c>cref</c> name by replacing
    /// angle brackets used in generic type arguments with curly braces (e.g. <c>List&lt;T&gt;</c> → <c>List{T}</c>).
    /// Angle brackets are not valid XML inside attribute values; curly braces are the documented convention.
    /// </summary>
    private static string ToXmlDocTypeName(string fullyQualified)
        => fullyQualified.Replace('<', '{').Replace('>', '}');


    /// <summary>
    /// Determines whether the character is a valid C# identifier character.
    /// </summary>
    private static bool IsIdentifierChar(char c) => char.IsLetterOrDigit(c) || c == '_';

    /// <summary>
    /// Emits nested ternary null checks for expression tree contexts where the
    /// null-conditional operator (<c>?.</c>) is not supported.
    /// </summary>
    private static void WriteExpressionTreeNavigation(
        IndentedStringBuilder builder,
        string parameterName,
        string[] path,
        bool[] segmentNullable,
        PropertyMapping property)
    {
        // find which segments need null checks
        var nullableIndices = new List<int>();
        for (int i = 0; i < path.Length; i++)
        {
            if (segmentNullable[i])
                nullableIndices.Add(i);
        }

        // determine fallback value
        string fallback;
        if (property.IsDestinationNullable)
            fallback = "null";
        else if (property.IsDestinationString)
            fallback = "string.Empty";
        else
            fallback = "default!";

        // build full access path: parameterName.path[0].path[1]...
        var fullAccess = parameterName;
        for (int i = 0; i < path.Length; i++)
            fullAccess = $"{fullAccess}.{path[i]}";

        // open nested ternaries from outermost nullable to innermost
        // each nullable segment i produces: prefix_up_to_i != null ? (...) : fallback
        var openCount = 0;
        for (int n = 0; n < nullableIndices.Count; n++)
        {
            var segIndex = nullableIndices[n];

            // build the prefix up to and including this segment
            var prefix = parameterName;
            for (int i = 0; i <= segIndex; i++)
                prefix = $"{prefix}.{path[i]}";

            builder.Append(prefix).Append(" != null ? ");

            // wrap inner expression in parens if there are more nullable segments
            if (n < nullableIndices.Count - 1)
                builder.Append("(");

            openCount++;
        }

        // emit the full access expression
        builder.Append(fullAccess);

        // close ternaries from innermost to outermost
        for (int n = nullableIndices.Count - 1; n >= 0; n--)
        {
            if (n < nullableIndices.Count - 1)
                builder.Append(")");

            builder.Append(" : ").Append(fallback);
        }
    }
}
