#pragma warning disable MA0051 // Method is too long

using Arbiter.Mapping.Generators.Infrastructure;
using Arbiter.Mapping.Generators.Models;

namespace Arbiter.Mapping.Generators;

/// <summary>
/// Emits the generated source code for a mapper partial class, including
/// <c>Map</c> and <c>ProjectTo</c> implementations with property assignments.
/// </summary>
public static class MapperWriter
{
    /// <summary>
    /// Generates the complete source text for a mapper partial class.
    /// </summary>
    /// <param name="mapperClass">The mapper model describing source, destination, and property mappings.</param>
    /// <returns>The generated C# source text.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="mapperClass"/> is <see langword="null"/>.</exception>
    public static string Generate(MapperClass mapperClass)
    {
        if (mapperClass is null)
            throw new ArgumentNullException(nameof(mapperClass));

        var builder = new IndentedStringBuilder();

        builder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine()
            .AppendLine("using System;")
            .AppendLine("using System.CodeDom.Compiler;")
            .AppendLine("using System.Linq;")
            .AppendLine("using System.Runtime.CompilerServices;")
            .AppendLine();

        builder
            .Append("namespace ")
            .Append(mapperClass.EntityNamespace)
            .AppendLine(";")
            .AppendLine();

        builder
            .AppendLine("/// <summary>")
            .Append("/// Source generated mapper from <see cref=\"")
            .Append(mapperClass.SourceClass.FullyQualified)
            .Append("\"/> to <see cref=\"")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .AppendLine("\"/>.")
            .AppendLine("/// </summary>")
            .Append("partial class ")
            .AppendLine(mapperClass.EntityName)
            .IncrementIndent()
            .Append(": global::Arbiter.Mapping.MapperProfile<")
            .Append(mapperClass.SourceClass.FullyQualified)
            .Append(", ")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .AppendLine(">")
            .DecrementIndent()
            .AppendLine("{")
            .IncrementIndent();

        // Generate the mapping method here
        GenerateCreateMapper(builder, mapperClass);
        GenerateCopyMapper(builder, mapperClass);
        GenerateProjectMapper(builder, mapperClass);

        // close class
        builder
            .DecrementIndent()
            .AppendLine("}");

        return builder.ToString();
    }


    /// <summary>
    /// Emits the <c>Map(TSource?)</c> implementation that creates a new destination instance.
    /// </summary>
    private static void GenerateCreateMapper(IndentedStringBuilder builder, MapperClass mapperClass)
    {
        builder
            .AppendLine("/// <inheritdoc />")
            .Append("[GeneratedCode(\"")
            .Append(ThisAssembly.AssemblyName)
            .Append("\", \"")
            .Append(ThisAssembly.FileVersion)
            .AppendLine("\")]")
            .AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]")
            .Append("public override ")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .Append("? Map(")
            .Append(mapperClass.SourceClass.FullyQualified)
            .AppendLine("? source)")
            .AppendLine("{")
            .IncrementIndent();

        // null check
        builder
            .AppendLine("if (source is null)")
            .AppendLine("    return default;");

        var ctorParams = mapperClass.ConstructorParameters.AsArray();

        if (ctorParams.Length > 0)
        {
            WriteConstructorCreation(builder, mapperClass, ctorParams, "source", isExpressionTree: false);
        }
        else
        {
            WriteInitializerCreation(builder, mapperClass, "source", isExpressionTree: false);
        }

        // function close
        builder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }

    /// <summary>
    /// Emits the <c>Map(TSource, TDestination)</c> implementation that copies values to an existing destination.
    /// When all non-ignored properties are init-only, emits a method that throws <see cref="NotSupportedException"/>.
    /// </summary>
    private static void GenerateCopyMapper(IndentedStringBuilder builder, MapperClass mapperClass)
    {
        var properties = mapperClass.Properties.AsArray();
        var hasAssignableProperties = false;

        foreach (var property in properties)
        {
            if (!property.IsIgnored && !property.IsReadOnly)
            {
                hasAssignableProperties = true;
                break;
            }
        }

        builder
            .AppendLine("/// <inheritdoc />")
            .Append("[GeneratedCode(\"")
            .Append(ThisAssembly.AssemblyName)
            .Append("\", \"")
            .Append(ThisAssembly.FileVersion)
            .AppendLine("\")]")
            .AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]")
            .Append("public override void Map(")
            .Append(mapperClass.SourceClass.FullyQualified)
            .Append(" source, ")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .AppendLine(" destination)")
            .AppendLine("{")
            .IncrementIndent();

        if (!hasAssignableProperties)
        {
            builder
                .AppendLine("throw new NotSupportedException(\"Map to existing destination is not supported because all destination properties are read-only.\");");
        }
        else
        {
            // null checks
            builder
                .AppendLine("if (source is null)")
                .AppendLine("    throw new ArgumentNullException(nameof(source));")
                .AppendLine()
                .AppendLine("if (destination is null)")
                .AppendLine("    throw new ArgumentNullException(nameof(destination));")
                .AppendLine();

            // foreach property mapping
            foreach (var property in mapperClass.Properties)
            {
                if (property.IsIgnored || property.IsReadOnly)
                    continue;

                builder.Append("destination.").Append(property.DestinationName).Append(" = ");
                WriteSourceExpression(builder, "source", property, isExpressionTree: false);
                builder.AppendLine(";");
            }
        }

        // function close
        builder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }

    /// <summary>
    /// Emits a static field that caches the projection expression and the <c>ProjectTo</c>
    /// implementation that references it, avoiding per-call expression tree allocations.
    /// </summary>
    private static void GenerateProjectMapper(IndentedStringBuilder builder, MapperClass mapperClass)
    {
        var ctorParams = mapperClass.ConstructorParameters.AsArray();

        // emit cached static expression field
        builder
            .Append("private static readonly System.Linq.Expressions.Expression<Func<")
            .Append(mapperClass.SourceClass.FullyQualified)
            .Append(", ")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .AppendLine(">> _projectExpression =");

        if (ctorParams.Length > 0)
        {
            WriteProjectConstructorExpression(builder, mapperClass, ctorParams);
        }
        else
        {
            WriteProjectInitializerExpression(builder, mapperClass);
        }

        // emit ProjectTo implementation
        builder
            .AppendLine("/// <inheritdoc />")
            .Append("[GeneratedCode(\"")
            .Append(ThisAssembly.AssemblyName)
            .Append("\", \"")
            .Append(ThisAssembly.FileVersion)
            .AppendLine("\")]")
            .Append("public override IQueryable<")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .Append("> ProjectTo(IQueryable<")
            .Append(mapperClass.SourceClass.FullyQualified)
            .AppendLine("> source)")
            .AppendLine("{")
            .IncrementIndent();

        // null check
        builder
            .AppendLine("if (source is null)")
            .AppendLine("    throw new ArgumentNullException(nameof(source));");

        // use cached expression
        builder
            .AppendLine()
            .AppendLine("return source.Select(_projectExpression);");

        // function close
        builder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }


    /// <summary>
    /// Emits the projection expression field body using constructor syntax:
    /// <c>src => new TDest(arg1, arg2, ...) { remaining = value, ... }</c>.
    /// </summary>
    private static void WriteProjectConstructorExpression(
        IndentedStringBuilder builder,
        MapperClass mapperClass,
        string[] ctorParams)
    {
        var ctorParamSet = new HashSet<string>(ctorParams, StringComparer.Ordinal);
        var propertyLookup = new Dictionary<string, PropertyMapping>(StringComparer.Ordinal);
        foreach (var property in mapperClass.Properties)
            propertyLookup[property.DestinationName] = property;

        builder
            .IncrementIndent()
            .Append("src => new ")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .AppendLine("(")
            .IncrementIndent();

        // emit constructor arguments
        for (var i = 0; i < ctorParams.Length; i++)
        {
            if (propertyLookup.TryGetValue(ctorParams[i], out var property) && !property.IsIgnored)
            {
                WriteSourceExpression(builder, "src", property, isExpressionTree: true);
            }
            else
            {
                builder.Append("default!");
            }

            if (i < ctorParams.Length - 1)
                builder.AppendLine(",");
        }

        builder.DecrementIndent();

        // collect remaining properties
        var remaining = new List<PropertyMapping>();
        foreach (var property in mapperClass.Properties)
        {
            if (property.IsIgnored || ctorParamSet.Contains(property.DestinationName))
                continue;

            remaining.Add(property);
        }

        if (remaining.Count > 0)
        {
            builder
                .AppendLine()
                .AppendLine(")")
                .AppendLine("{")
                .IncrementIndent();

            foreach (var property in remaining)
            {
                builder.Append(property.DestinationName).Append(" = ");
                WriteSourceExpression(builder, "src", property, isExpressionTree: true);
                builder.AppendLine(",");
            }

            builder
                .DecrementIndent()
                .AppendLine("};");
        }
        else
        {
            builder.AppendLine().AppendLine(");");
        }

        builder
            .DecrementIndent()
            .AppendLine();
    }

    /// <summary>
    /// Emits the projection expression field body using object initializer syntax:
    /// <c>src => new TDest { Prop = value, ... }</c>.
    /// </summary>
    private static void WriteProjectInitializerExpression(
        IndentedStringBuilder builder,
        MapperClass mapperClass)
    {
        builder
            .IncrementIndent()
            .Append("src => new ")
            .AppendLine(mapperClass.DestinationClass.FullyQualified)
            .AppendLine("{")
            .IncrementIndent();

        foreach (var property in mapperClass.Properties)
        {
            if (property.IsIgnored)
                continue;

            builder.Append(property.DestinationName).Append(" = ");
            WriteSourceExpression(builder, "src", property, isExpressionTree: true);
            builder.AppendLine(",");
        }

        builder
            .DecrementIndent()
            .AppendLine("};")
            .DecrementIndent()
            .AppendLine();
    }


    /// <summary>
    /// Emits a <c>return new TDest(arg1, arg2, ...) { remaining = value, ... };</c> statement
    /// using constructor arguments for matched parameters and an object initializer for the rest.
    /// </summary>
    private static void WriteConstructorCreation(
        IndentedStringBuilder builder,
        MapperClass mapperClass,
        string[] ctorParams,
        string parameterName,
        bool isExpressionTree)
    {
        var ctorParamSet = new HashSet<string>(ctorParams, StringComparer.Ordinal);
        var propertyLookup = new Dictionary<string, PropertyMapping>(StringComparer.Ordinal);

        foreach (var property in mapperClass.Properties)
            propertyLookup[property.DestinationName] = property;

        // open constructor call
        builder
            .AppendLine()
            .Append("return new ")
            .Append(mapperClass.DestinationClass.FullyQualified)
            .AppendLine("(")
            .IncrementIndent();

        // emit constructor arguments in parameter order
        for (var i = 0; i < ctorParams.Length; i++)
        {
            if (propertyLookup.TryGetValue(ctorParams[i], out var property) && !property.IsIgnored)
            {
                WriteSourceExpression(builder, parameterName, property, isExpressionTree);
            }
            else
            {
                builder.Append("default!");
            }

            if (i < ctorParams.Length - 1)
                builder.AppendLine(",");
        }

        builder.DecrementIndent();

        // collect remaining properties not covered by the constructor
        var remaining = new List<PropertyMapping>();
        foreach (var property in mapperClass.Properties)
        {
            if (property.IsIgnored || ctorParamSet.Contains(property.DestinationName))
                continue;

            remaining.Add(property);
        }

        if (remaining.Count > 0)
        {
            // close constructor, open initializer
            builder
                .AppendLine()
                .AppendLine(")")
                .AppendLine("{")
                .IncrementIndent();

            foreach (var property in remaining)
            {
                builder.Append(property.DestinationName).Append(" = ");
                WriteSourceExpression(builder, parameterName, property, isExpressionTree);
                builder.AppendLine(",");
            }

            builder
                .DecrementIndent()
                .AppendLine("};");
        }
        else
        {
            // close constructor only
            builder.AppendLine().AppendLine(");");
        }
    }

    /// <summary>
    /// Emits a <c>return new TDest { Prop = value, ... };</c> statement using object initializer syntax.
    /// </summary>
    private static void WriteInitializerCreation(
        IndentedStringBuilder builder,
        MapperClass mapperClass,
        string parameterName,
        bool isExpressionTree)
    {
        // open object initializer
        builder
            .AppendLine()
            .Append("return new ")
            .AppendLine(mapperClass.DestinationClass.FullyQualified)
            .AppendLine("{")
            .IncrementIndent();

        // foreach property mapping
        foreach (var property in mapperClass.Properties)
        {
            if (property.IsIgnored)
                continue;

            builder.Append(property.DestinationName).Append(" = ");
            WriteSourceExpression(builder, parameterName, property, isExpressionTree);
            builder.AppendLine(",");
        }

        // close object initializer
        builder
            .DecrementIndent()
            .AppendLine("};");
    }


    /// <summary>
    /// Writes the source-side expression for a single property assignment, choosing between
    /// raw expressions, null-safe navigation, or direct property access.
    /// </summary>
    private static void WriteSourceExpression(
        IndentedStringBuilder builder,
        string parameterName,
        PropertyMapping property,
        bool isExpressionTree)
    {
        // raw expression mode: emit directly with parameter substitution
        if (!string.IsNullOrEmpty(property.SourceExpression))
        {
            WriteRawExpression(builder, parameterName, property);
            return;
        }

        var path = property.SourcePath.AsArray();
        if (path.Length == 0)
            return;

        var segmentNullable = property.SourceSegmentNullable.AsArray();
        var hasAnyNullable = Array.Exists(segmentNullable, static n => n);

        if (path.Length > 1 && hasAnyNullable && isExpressionTree)
        {
            // expression trees don't support ?. operator (CS8072)
            // use nested ternaries for each nullable segment
            WriteExpressionTreeNavigation(builder, parameterName, path, segmentNullable, property);
        }
        else if (path.Length > 1 && hasAnyNullable)
        {
            // in-memory null safety: use ?. only after nullable segments
            builder.Append(parameterName);

            for (int i = 0; i < path.Length; i++)
            {
                // use ?. before this segment if the previous segment is nullable
                var nullConditional = i > 0 && segmentNullable[i - 1];
                builder.Append(nullConditional ? "?." : ".").Append(path[i]);
            }

            if (property.IsDestinationNullable)
            {
                // destination allows null, no fallback needed
            }
            else if (property.IsDestinationString)
            {
                builder.Append(" ?? string.Empty");
            }
            else
            {
                builder.Append(" ?? default!");
            }
        }
        else
        {
            // direct property access: source.Id or source.Tenant.Name
            builder.Append(parameterName);
            for (int i = 0; i < path.Length; i++)
                builder.Append(".").Append(path[i]);
        }
    }

    /// <summary>
    /// Emits a raw source expression with lambda parameter name substitution.
    /// </summary>
    private static void WriteRawExpression(
        IndentedStringBuilder builder,
        string parameterName,
        PropertyMapping property)
    {
        var expression = property.SourceExpression;
        var sourceParam = property.SourceExpressionParameter;

        // substitute the lambda parameter name with the target parameter name
        if (!string.IsNullOrEmpty(sourceParam)
            && !string.Equals(sourceParam, parameterName, StringComparison.Ordinal))
        {
            expression = expression.Replace(
                sourceParam + ".",
                parameterName + ".");
        }

        builder.Append(expression);
    }

    /// <summary>
    /// Emits nested ternary null checks for expression tree contexts where the
    /// null-conditional operator (<c>?.</c>) is not supported.
    /// </summary>
    private static void WriteExpressionTreeNavigation(
        IndentedStringBuilder builder,
        string parameterName,
        string[] path,
        bool[] segmentNullable,
        PropertyMapping property)
    {
        // find which segments need null checks
        var nullableIndices = new List<int>();
        for (int i = 0; i < path.Length; i++)
        {
            if (segmentNullable[i])
                nullableIndices.Add(i);
        }

        // determine fallback value
        string fallback;
        if (property.IsDestinationNullable)
            fallback = "null";
        else if (property.IsDestinationString)
            fallback = "string.Empty";
        else
            fallback = "default!";

        // build full access path: parameterName.path[0].path[1]...
        var fullAccess = parameterName;
        for (int i = 0; i < path.Length; i++)
            fullAccess = $"{fullAccess}.{path[i]}";

        // open nested ternaries from outermost nullable to innermost
        // each nullable segment i produces: prefix_up_to_i != null ? (...) : fallback
        var openCount = 0;
        for (int n = 0; n < nullableIndices.Count; n++)
        {
            var segIndex = nullableIndices[n];

            // build the prefix up to and including this segment
            var prefix = parameterName;
            for (int i = 0; i <= segIndex; i++)
                prefix = $"{prefix}.{path[i]}";

            builder.Append(prefix).Append(" != null ? ");

            // wrap inner expression in parens if there are more nullable segments
            if (n < nullableIndices.Count - 1)
                builder.Append("(");

            openCount++;
        }

        // emit the full access expression
        builder.Append(fullAccess);

        // close ternaries from innermost to outermost
        for (int n = nullableIndices.Count - 1; n >= 0; n--)
        {
            if (n < nullableIndices.Count - 1)
                builder.Append(")");

            builder.Append(" : ").Append(fallback);
        }
    }
}
