using System.Collections.Generic;
using System.Text.Json.Serialization;

using Arbiter.CommandQuery.Commands;
using Arbiter.CommandQuery.Queries;

using Tracker.Domain.Models;

namespace Tracker.Domain;

/// <summary>
/// Represents the JSON serialization context for the domain models, commands, and queries.
/// This class is used to configure and generate source code for JSON serialization
/// using System.Text.Json's source generation feature.
/// </summary>
/// <remarks>
/// The declarations inside the <c>#region Generated Attributes</c> are automatically generated by a template.
/// Avoid modifying these entries manually as changes may be overwritten.
/// </remarks>
[JsonSourceGenerationOptions(
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
#region Generated Attributes
// 'Priority' Models, Commands and Queries
[JsonSerializable(typeof(PriorityReadModel))]
[JsonSerializable(typeof(EntityIdentifierQuery<int, PriorityReadModel>))]
[JsonSerializable(typeof(EntityIdentifiersQuery<int, PriorityReadModel>))]
[JsonSerializable(typeof(EntityPagedQuery<PriorityReadModel>))]
[JsonSerializable(typeof(IReadOnlyList<PriorityReadModel>))]
[JsonSerializable(typeof(EntityPagedResult<PriorityReadModel>))]
[JsonSerializable(typeof(PriorityCreateModel))]
[JsonSerializable(typeof(EntityCreateCommand<PriorityCreateModel, PriorityReadModel>))]
[JsonSerializable(typeof(PriorityUpdateModel))]
[JsonSerializable(typeof(EntityIdentifierQuery<int, PriorityUpdateModel>))]
[JsonSerializable(typeof(EntityUpdateCommand<int, PriorityUpdateModel, PriorityReadModel>))]
[JsonSerializable(typeof(EntityPatchCommand<int, PriorityReadModel>))]
[JsonSerializable(typeof(EntityDeleteCommand<int, PriorityReadModel>))]
// 'Status' Models, Commands and Queries
[JsonSerializable(typeof(StatusReadModel))]
[JsonSerializable(typeof(EntityIdentifierQuery<int, StatusReadModel>))]
[JsonSerializable(typeof(EntityIdentifiersQuery<int, StatusReadModel>))]
[JsonSerializable(typeof(EntityPagedQuery<StatusReadModel>))]
[JsonSerializable(typeof(IReadOnlyList<StatusReadModel>))]
[JsonSerializable(typeof(EntityPagedResult<StatusReadModel>))]
[JsonSerializable(typeof(StatusCreateModel))]
[JsonSerializable(typeof(EntityCreateCommand<StatusCreateModel, StatusReadModel>))]
[JsonSerializable(typeof(StatusUpdateModel))]
[JsonSerializable(typeof(EntityIdentifierQuery<int, StatusUpdateModel>))]
[JsonSerializable(typeof(EntityUpdateCommand<int, StatusUpdateModel, StatusReadModel>))]
[JsonSerializable(typeof(EntityPatchCommand<int, StatusReadModel>))]
[JsonSerializable(typeof(EntityDeleteCommand<int, StatusReadModel>))]
// 'Task' Models, Commands and Queries
[JsonSerializable(typeof(TaskReadModel))]
[JsonSerializable(typeof(EntityIdentifierQuery<int, TaskReadModel>))]
[JsonSerializable(typeof(EntityIdentifiersQuery<int, TaskReadModel>))]
[JsonSerializable(typeof(EntityPagedQuery<TaskReadModel>))]
[JsonSerializable(typeof(IReadOnlyList<TaskReadModel>))]
[JsonSerializable(typeof(EntityPagedResult<TaskReadModel>))]
[JsonSerializable(typeof(TaskCreateModel))]
[JsonSerializable(typeof(EntityCreateCommand<TaskCreateModel, TaskReadModel>))]
[JsonSerializable(typeof(TaskUpdateModel))]
[JsonSerializable(typeof(EntityIdentifierQuery<int, TaskUpdateModel>))]
[JsonSerializable(typeof(EntityUpdateCommand<int, TaskUpdateModel, TaskReadModel>))]
[JsonSerializable(typeof(EntityPatchCommand<int, TaskReadModel>))]
[JsonSerializable(typeof(EntityDeleteCommand<int, TaskReadModel>))]
// 'Tenant' Models, Commands and Queries
[JsonSerializable(typeof(TenantReadModel))]
[JsonSerializable(typeof(EntityIdentifierQuery<int, TenantReadModel>))]
[JsonSerializable(typeof(EntityIdentifiersQuery<int, TenantReadModel>))]
[JsonSerializable(typeof(EntityPagedQuery<TenantReadModel>))]
[JsonSerializable(typeof(IReadOnlyList<TenantReadModel>))]
[JsonSerializable(typeof(EntityPagedResult<TenantReadModel>))]
[JsonSerializable(typeof(TenantCreateModel))]
[JsonSerializable(typeof(EntityCreateCommand<TenantCreateModel, TenantReadModel>))]
[JsonSerializable(typeof(TenantUpdateModel))]
[JsonSerializable(typeof(EntityIdentifierQuery<int, TenantUpdateModel>))]
[JsonSerializable(typeof(EntityUpdateCommand<int, TenantUpdateModel, TenantReadModel>))]
[JsonSerializable(typeof(EntityPatchCommand<int, TenantReadModel>))]
[JsonSerializable(typeof(EntityDeleteCommand<int, TenantReadModel>))]
// 'User' Models, Commands and Queries
[JsonSerializable(typeof(UserReadModel))]
[JsonSerializable(typeof(EntityIdentifierQuery<int, UserReadModel>))]
[JsonSerializable(typeof(EntityIdentifiersQuery<int, UserReadModel>))]
[JsonSerializable(typeof(EntityPagedQuery<UserReadModel>))]
[JsonSerializable(typeof(IReadOnlyList<UserReadModel>))]
[JsonSerializable(typeof(EntityPagedResult<UserReadModel>))]
[JsonSerializable(typeof(UserCreateModel))]
[JsonSerializable(typeof(EntityCreateCommand<UserCreateModel, UserReadModel>))]
[JsonSerializable(typeof(UserUpdateModel))]
[JsonSerializable(typeof(EntityIdentifierQuery<int, UserUpdateModel>))]
[JsonSerializable(typeof(EntityUpdateCommand<int, UserUpdateModel, UserReadModel>))]
[JsonSerializable(typeof(EntityPatchCommand<int, UserReadModel>))]
[JsonSerializable(typeof(EntityDeleteCommand<int, UserReadModel>))]
// Common Models, Commands and Queries
[JsonSerializable(typeof(EntityQuery))]
[JsonSerializable(typeof(EntityFilter))]
[JsonSerializable(typeof(EntitySort))]
#endregion
// Manual Declarations
public partial class DomainJsonContext : JsonSerializerContext
{
    // class generated by System.Text.Json source generation
}

